# Profile por dafault
spring:
  application:
    name: validatorInventoryIUOMongo
  data:
    mongodb:
      uri: ****
  profiles:
    active: qa


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.data.mongodb.core.query: INFO
    org.mongodb.driver.protocol: INFO
    org.mongodb.driver.cluster: INFO

---

# Perfil QA
---
spring:
  profiles: qa

datasource:
  primary:
    jdbc-url: ****
    username: ****
    password: ****
    driver-class-name: oracle.jdbc.OracleDriver
  secondary:
    jdbc-url: ****
    username: ****
    password: ****
    driver-class-name: oracle.jdbc.OracleDriver

# Enviroment QA
config:
  atgCataSchema: QA2CATA
  atgCoreSchema: QA2CORE
  iuoSchema: APL_INVUN
  threads: 1
  batchSize: 300
  numberBatches: 1

---

# Perfil PROD
---
spring:
  profiles: prod

datasource:
  primary:
    jdbc-url: ****
    username: ****
    password: ****
    driver-class-name: oracle.jdbc.OracleDriver
  secondary:
    jdbc-url: ****
    username: ****
    password: ****
    driver-class-name: oracle.jdbc.OracleDriver

# Enviroment PROD
config:
  atgCataSchema: ATGCATA
  atgCoreSchema: ATGCORE
  iuoSchema: APL_INVUN
  threads: 1
  batchSize: 300
  numberBatches: 1